### ISSUE TITLE
Hide/Show Code & List buttons don't work (but Key is fine)

### ISSUE THREAD

**Issue by kawilliams** [kawilliams/expression-trees#6]
@alex-r-bigelow could you take a look at this?

Hide Code View only closes the code view but doesn't reopen it.

Hide Node List isn't hoverable. When you mouseover and then click, Hide Code View changes color and then the code view collapses. The primitive list remains the same.

**Comment by kawilliams** [comment]
Ah nevermind, left the developer window open and it was limiting my mouse interaction.

**Comment by alex-r-bigelow** [comment]
Sorry; didn't see this until now. Glad it worked!

**Comment by stevenrbrandt** [comment]
Is the current branch master or alex tweaks? Thanks.
--Steve

**Comment by alex-r-bigelow** [comment]
Sorry, my stuff has been merged at this point; I forgot to delete the branch / fork...
